background {
    monitor =
    path = ~/Pictures/Wallpapers/gentoo.png
    blur_passes = 3
    blur_size = 8
    brightness = 0.55
}

general {
    disable_loading_bar = true
    hide_cursor = true
    no_fade_in = false
    no_fade_out = false
}

input-field {
    monitor =
    size = 340, 60
    position = 0, -70

    halign = center
    valign = center

    inner_color = rgba(30, 30, 46, 0.90)
    outer_color = rgba(203, 166, 247, 0.85)

    font_color = rgb(cdd6f4)

    fade_on_empty = false
    rounding = 16
    outline_thickness = 2

    placeholder_text = <span foreground="##a6adc8">Password...</span>
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M')"

    color = rgb(cdd6f4)
    font_size = 72
    font_family = JetBrainsMono Nerd Font

    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date '+%A, %d %B')"

    color = rgb(a6adc8)
    font_size = 18
    font_family = JetBrainsMono Nerd Font

    position = 0, 20
    halign = center
    valign = center
}
